#!/usr/bin/env node
/**
 * Generates an RSA key pair for Snowflake key-pair authentication.
 *
 * Writes:
 *   keys/snowflake_key.p8      unencrypted PKCS#8 private key (or encrypted if --passphrase)
 *   keys/snowflake_key.pub     SPKI public key (what you register on the Snowflake user)
 *
 * The whole keys/ directory is gitignored.
 *
 * Usage:
 *   node scripts/generate-keypair.js
 *   node scripts/generate-keypair.js --passphrase "my secret"
 *   node scripts/generate-keypair.js --force        # overwrite existing keys
 *
 * Snowflake requires an RSA key of at least 2048 bits; we use 2048 (Snowflake's
 * documented recommendation) in PKCS#8 format, which is what the Node driver expects.
 */
const crypto = require('node:crypto');
const fs = require('node:fs');
const path = require('node:path');

const argv = process.argv.slice(2);
const getFlag = (name) => {
  const i = argv.indexOf(`--${name}`);
  return i === -1 ? undefined : argv[i + 1];
};
const hasFlag = (name) => argv.includes(`--${name}`);

const passphrase = getFlag('passphrase');
const force = hasFlag('force');

const KEYS_DIR = path.resolve(__dirname, '..', '..', 'keys');
const PRIVATE_PATH = path.join(KEYS_DIR, 'snowflake_key.p8');
const PUBLIC_PATH = path.join(KEYS_DIR, 'snowflake_key.pub');

fs.mkdirSync(KEYS_DIR, { recursive: true });

for (const p of [PRIVATE_PATH, PUBLIC_PATH]) {
  if (fs.existsSync(p) && !force) {
    console.error(
      `Refusing to overwrite existing key: ${p}\n` +
        `Re-run with --force if you really want to replace it.\n` +
        `NOTE: replacing the key means you must re-register the new public key in Snowflake.`
    );
    process.exit(1);
  }
}

const privateKeyEncoding = passphrase
  ? { type: 'pkcs8', format: 'pem', cipher: 'aes-256-cbc', passphrase }
  : { type: 'pkcs8', format: 'pem' };

const { publicKey, privateKey } = crypto.generateKeyPairSync('rsa', {
  modulusLength: 2048,
  publicKeyEncoding: { type: 'spki', format: 'pem' },
  privateKeyEncoding,
});

// 0o600 is a no-op on Windows ACLs but correct and harmless; matters if this
// repo is ever cloned/run on Linux or in a container.
fs.writeFileSync(PRIVATE_PATH, privateKey, { mode: 0o600 });
fs.writeFileSync(PUBLIC_PATH, publicKey, { mode: 0o644 });

// Snowflake wants the base64 body only -- no PEM header/footer, no newlines.
const publicKeyBody = publicKey
  .replace('-----BEGIN PUBLIC KEY-----', '')
  .replace('-----END PUBLIC KEY-----', '')
  .replace(/\s+/g, '');

const user = process.env.SNOWFLAKE_USER || 'GOWTHAM';

console.log(`\nKey pair written:`);
console.log(`  private : ${PRIVATE_PATH}${passphrase ? ' (encrypted)' : ' (unencrypted)'}`);
console.log(`  public  : ${PUBLIC_PATH}`);
if (passphrase) {
  console.log(`\nSet SNOWFLAKE_PRIVATE_KEY_PASSPHRASE in backend/.env to the passphrase you used.`);
}
console.log(`\n${'='.repeat(72)}`);
console.log(`Run this SQL in Snowflake as a role that can ALTER the user`);
console.log(`(ACCOUNTADMIN/USERADMIN, or the user themselves via SECURITYADMIN):`);
console.log(`${'='.repeat(72)}\n`);
console.log(`ALTER USER ${user} SET RSA_PUBLIC_KEY='${publicKeyBody}';\n`);
console.log(`-- Then verify the fingerprint was stored:`);
console.log(`DESC USER ${user};`);
console.log(`-- Look for the RSA_PUBLIC_KEY_FP property in the output.\n`);
console.log(`${'='.repeat(72)}`);
console.log(`Locally computed fingerprint (should match RSA_PUBLIC_KEY_FP above):`);
const fp = crypto
  .createHash('sha256')
  .update(crypto.createPublicKey(publicKey).export({ type: 'spki', format: 'der' }))
  .digest('base64');
console.log(`  SHA256:${fp}`);
console.log(`${'='.repeat(72)}\n`);

// Also write the SQL to a gitignored file so it is easy to copy/paste later.
const sqlPath = path.join(KEYS_DIR, 'register-public-key.sql');
fs.writeFileSync(
  sqlPath,
  `-- Generated by scripts/generate-keypair.js\n` +
    `-- Register the public key on the Snowflake user for key-pair auth.\n` +
    `-- Expected fingerprint: SHA256:${fp}\n\n` +
    `ALTER USER ${user} SET RSA_PUBLIC_KEY='${publicKeyBody}';\n\n` +
    `DESC USER ${user};\n`
);
console.log(`Same SQL saved to: ${sqlPath} (gitignored)\n`);
