/**
 * Dashboard descriptor: the single source of truth for which columns are
 * measures, which are drillable dimensions, and which is the time axis.
 *
 * Generated by `npm run introspect` into backend/dashboard.config.json and
 * hand-editable afterwards.
 *
 * SECURITY: every table/column identifier used in generated SQL comes from this
 * descriptor -- which itself comes from INFORMATION_SCHEMA -- and never from an
 * HTTP request. Requests may only reference descriptor *keys*, which we resolve
 * to identifiers here. That is what makes identifier interpolation safe; filter
 * *values* are always passed as bind parameters.
 */
const fs = require('node:fs');
const path = require('node:path');
const config = require('./env');
const logger = require('../util/logger');

const DESCRIPTOR_PATH = path.join(config.paths.backendRoot, 'dashboard.config.json');

const VALID_AGGS = new Set(['SUM', 'COUNT', 'COUNT_DISTINCT', 'AVG', 'MIN', 'MAX']);
// Snowflake unquoted identifier rules; we quote anyway, but reject anything
// exotic so a hand-edited descriptor cannot smuggle SQL into an identifier.
const SAFE_IDENTIFIER = /^[A-Za-z_][A-Za-z0-9_$]*$/;

let cached = null;

function assertIdentifier(value, what) {
  if (value === '*') return value;
  if (typeof value !== 'string' || !SAFE_IDENTIFIER.test(value)) {
    throw new Error(
      `Invalid ${what} in dashboard.config.json: ${JSON.stringify(value)}. ` +
        `Identifiers must match ${SAFE_IDENTIFIER}.`
    );
  }
  return value;
}

function normalize(raw) {
  const source = raw.source || {};
  ['database', 'schema', 'object'].forEach((k) => assertIdentifier(source[k], `source.${k}`));

  const dimensions = (raw.dimensions || []).map((d) => ({
    key: d.key,
    label: d.label || d.key,
    column: assertIdentifier(d.column, `dimension "${d.key}" column`),
    approxDistinct: d.approxDistinct ?? null,
  }));

  const measures = (raw.measures || []).map((m) => {
    const agg = String(m.agg || 'SUM').toUpperCase();
    if (!VALID_AGGS.has(agg)) {
      throw new Error(
        `Invalid agg "${m.agg}" for measure "${m.key}". Allowed: ${[...VALID_AGGS].join(', ')}`
      );
    }
    if (agg !== 'COUNT') assertIdentifier(m.column, `measure "${m.key}" column`);
    return {
      key: m.key,
      label: m.label || m.key,
      column: m.column,
      agg,
      format: m.format || 'number',
    };
  });

  const timeColumns = (raw.timeColumns || []).map((t) => ({
    key: t.key,
    label: t.label || t.key,
    column: assertIdentifier(t.column, `timeColumn "${t.key}" column`),
    type: t.type || 'DATE',
  }));

  const detailColumns = (raw.detailColumns || []).map((c) =>
    assertIdentifier(c, 'detailColumns entry')
  );

  if (measures.length === 0) {
    throw new Error('dashboard.config.json defines no measures.');
  }

  const dimensionKeys = new Set(dimensions.map((d) => d.key));
  const drillPath = (raw.drillPath || []).filter((k) => dimensionKeys.has(k));

  return {
    source,
    fqn: `"${source.database}"."${source.schema}"."${source.object}"`,
    dimensions,
    measures,
    timeColumns,
    defaultTimeColumn: raw.defaultTimeColumn || (timeColumns[0] ? timeColumns[0].key : null),
    drillPath,
    detailColumns,
    generatedFrom: raw.generatedFrom || null,

    dimension: (key) => dimensions.find((d) => d.key === key),
    measure: (key) => measures.find((m) => m.key === key),
    timeColumn: (key) => timeColumns.find((t) => t.key === key),
  };
}

/** True when `npm run introspect` has produced a descriptor. */
function isConfigured() {
  return fs.existsSync(DESCRIPTOR_PATH);
}

function load({ reload = false } = {}) {
  if (cached && !reload) return cached;
  if (!isConfigured()) {
    throw new Error(
      `Dashboard is not configured yet: ${DESCRIPTOR_PATH} is missing.\n` +
        `Run:  cd backend && npm run introspect`
    );
  }
  const raw = JSON.parse(fs.readFileSync(DESCRIPTOR_PATH, 'utf8'));
  cached = normalize(raw);
  logger.info(
    `Dashboard descriptor loaded: ${cached.source.object} ` +
      `(${cached.measures.length} measures, ${cached.dimensions.length} dimensions)`
  );
  return cached;
}

module.exports = { load, isConfigured, DESCRIPTOR_PATH };
